import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import Providers from '@/components/Providers'
import { Toaster } from 'react-hot-toast'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfolio AI',
  description: 'Generated by create next app',
  icons: 'portfolioAILogo.ico',
  // icons: {
  //   icon: '/icon.png',
  // },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <Providers>
        {/* Wrapping in react-query */}
        <html lang="en">

          <body className={inter.className}>
            {/* <link rel="icon" href="/portfolioAILogo.ico" sizes="any" /> */}
            {children}
          </body>
          <Toaster />
        </html>
      </Providers>
    </ClerkProvider>
  )
}
